name: CityJSON QGIS Plugin Test Suite

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QGIS environment 
        run: |
          sudo apt update
          sudo apt install -y qgis python3-qgis python3-pyqt5 python3-pytest
      
      - name: Set Environment Variables
        run: |
          echo "QGIS_HOME=/usr" >> $GITHUB_ENV
          echo "QT_QPA_PLATFORM=offscreen" >> $GITHUB_ENV
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Start Virtual Display
        run: Xvfb :99 -screen 0 1024x768x24 &

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

      - name: Run tests with coverage
        run: |
          python -m pytest tests/ -v -s --cov=core/ --cov=gui